name: CI

on:
  push:
    branches:
      - main
      - next
    workflow_dispatch:

jobs:
  build:
    uses: vfourny/.github/.github/workflows/build.yml@main
    with:
      is_build: true
  deploy_dev:
    needs: build
    uses: vfourny/.github/.github/workflows/deploy_railway.yml@main
    with:
      railway_deploy_token: ${{ secrets.RAILWAY_DEPLOY_TOKEN }}
  release:
    needs: [build, deploy_dev]
    if: github.event_name == 'workflow_dispatch'
    uses: vfourny/.github/.github/workflows/release.yml@main
    with:
      is_publish: true
      is_build: true
    secrets:
      SEMANTIC_BOT_APP_ID: ${{ secrets.SEMANTIC_BOT_APP_ID }}
      SEMANTIC_BOT_PRIVATE_KEY: ${{ secrets.SEMANTIC_BOT_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
